export const Leagues = {
  FRANCE_LIGUE_1: "FRANCE_LIGUE_1",
  FRANCE_LIGUE_2: "FRANCE_LIGUE_2",
  MEXICO_LIGA_MX: "MEXICO_LIGA_MX",
  MEXICO_ASCENSO_MX: "MEXICO_ASCENSO_MX",
  UNITED_STATES_MAJOR_LEAGUE_SOCCER: "UNITED_STATES_MAJOR_LEAGUE_SOCCER",
};
