export const Stats = {
  AGGRESSIVENESS: "SPEED",
  DRIBBLING: "SPEED",
  BALANCE: "BALANCE",
  FINISHING: "FINISHING",
  PACE: "SPRINT_SPEED",
  PASSING: "SPEED",
  PHYSICAL_PROWESS: "SPEED",
  REACTIONS: "SPEED",
  SHOOTING: "SPEED",
  SPEED: "SPEED",
  SPRINT_SPEED: "SPRINT_SPEED",
  STAMINA: "SPEED",
  STRENGHT: "STRENGTH",
  VISION: "VISION",
};

export const SoftStats = {
  HARDWORKING: "HARDWORKING",
  DETERMINED: "DETERMINED",
  LOYAL: "LOYAL",
  TEAM_PLAYER: "TEAM_PLAYER",
  HUMBLE: "HUMBLE",
  CONFIDENT: "CONFIDENT",
  OUTSPOKEN: "OUTSPOKEN",
  UNPREDICTABLE: "UNPREDICTABLE",
  EMOTIONAL: "EMOTIONAL",
  CONTROVERSIAL: "CONTROVERSIAL",
};
